# Étape 2 - Effectuez le pré-processing des données Open Agenda
#### Description
Récupérer les données d'événements à partir de la plateforme Open Agenda, les filtrer par localisation et période, et structurer ces données pour une utilisation future dans la base de données vectorielle.
#### Résultat attendu
Un jeu de données d'événements propre et structuré, prêt à être indexé. Vous pourrez effectuer des tests unitaires pour vous assurer d’avoir récupérer les données attendues.
#### Recommandations
- Utiliser l'API Open Agenda pour récupérer les événements.
- Filtrer les événements par localisation et période (1 an d'historique et événements à venir).
- Convertir les descriptions des événements en format vectoriel avec un modèle de NLP comme Mistral.

## Librairies nécessaires

In [4]:
# Imports standards
import faiss
import requests
import pandas as pd
import numpy as np

# Imports LangChain
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings # ou SentenceTransformerEmbeddings
from langchain_text_splitters import RecursiveCharacterTextSplitter

from sentence_transformers import SentenceTransformer


# Import Mistral
from mistralai.client import MistralClient

import os
from dotenv import load_dotenv
from mistralai import Mistral

## Récupération des données via l'API d'Open Agenda
Nou avons fait le choix de prendre la ville de Paris pour ce POC. L'objectif est de pouvoir montrer que le poc fonctionne pour une grande ville et pourra être généralisable à plusieurs villes puis plusieurs pays etc.

Paris est un choix raisonné car c'est une ville avec beaucoup d'évènements culturels.
Dans un premier temps nous allons nous focaliser sur 100 lignes afin de contrôler la cohérence de nos éléments.
Pour le filtre de temps, nous prenons la variable "lastdate_end" afin d'avoir les bonnes dates de fin d'un événement.
Nous fixons la temporalité entre le 01/01/2025 et 01/01/2027 pour obtenir l'historique des informations sur 1 an + les informations sur l'année 2026 à venir.

#### Récupérons des informations depuis l'API, 100 lignes pour le moment.

In [5]:
# Chemin pour l'API d'Open Agenda sur le dataset des évènements publics
url = "https://public.opendatasoft.com/api/explore/v2.1/catalog/datasets/evenements-publics-openagenda/records"

params = {
    "limit": 100,
    "lang": "fr",
    # Choix de la localisation à Paris
    "refine": ["location_city:Paris"],
    "where": (
        # lastdate_end = dernière date à laquelle se termine l’évènement
        # Choix de prendre des évènements qui finissent après le 01/01/2025
        "lastdate_end >= '2025-01-01' "
        # Prendre les évènements en  compte jusqu'avril 2026
        "AND lastdate_end <= '2026-04-01'"
    ),
    # Classé par ordre décroissant afin d'avoir des données en 2025 et 2026
    "order_by": "lastdate_end desc"
}

response = requests.get(url, params=params)
response.raise_for_status()
data = response.json()

df = pd.DataFrame(data.get("results"))
df.head()

,uid,slug,canonicalurl,title_fr,description_fr,longdescription_fr,conditions_fr,keywords_fr,image,imagecredits,...,originagenda_uid,contributor_email,contributor_contactnumber,contributor_contactname,contributor_contactposition,contributor_organization,category,country_fr,registration,links
0,66000118,kohlhaas-4508066,https://openagenda.com/culture/events/kohlhaas...,Kohlhaas,estrarre - Julien Kosellek,"<p>À la frontière du théâtre et du conte, Kohl...",Entrée libre sur réservation pour les experts ...,"[Récit, Narration, von Kleist, Révolte, injust...",https://cdn.openagenda.com/main/418694f0481849...,© Paola Valentin,...,97606842,None,None,None,None,None,None,France (Métropole),"[{""type"": ""email"", ""value"": ""production@estrar...","[{""link"": ""http://estrarre.fr""}, {""data"": {""au..."
1,80142793,representation-moi-elles,https://openagenda.com/culture/events/represen...,"Représentation - Moi, Elles",Cie Abricotier d'Argent - Jing WANG,"<p><em>Moi, Elles</em> est une pièce de théâtr...",Sur inscription,None,https://cdn.openagenda.com/main/abf7143914cf4c...,None,...,97606842,None,None,None,None,None,None,France (Métropole),"[{""type"": ""email"", ""value"": ""hybriditesfrancec...",None
2,63232931,ascanio-in-alba-mozart,https://openagenda.com/culture/events/ascanio-...,"LES TALENS LYRIQUES - Ascanio in Alba, Mozart",Christophe Rousset,<p>Festa teatrale en deux actes à Milan au Reg...,None,None,https://cdn.openagenda.com/main/279a69ad076d47...,None,...,73237661,None,None,None,None,None,None,France (Métropole),"[{""type"": ""link"", ""value"": ""https://25-26.thea...",None
3,5148482,les-lundis-musicaux-contes,https://openagenda.com/culture/events/les-lund...,LE BALCON : LES LUNDIS MUSICAUX - Contes,Après avoir enflammé les planches de l’Athénée...,<p>Après avoir enflammé les planches de l’Athé...,12 à 30€,"[Les Lundis Musicaux, Sandrine Piau, David Kad...",https://cdn.openagenda.com/main/47d78f825f3f4f...,Lilli Lacombe,...,73237661,None,None,None,None,None,None,France (Métropole),"[{""type"": ""link"", ""value"": ""https://athenee-th...",None
4,1617629,maison-de-poupee-6574989,https://openagenda.com/culture/events/maison-d...,Maison de Poupée,Plexus Polaire / Yngvild Aspeli,<p>“Tout a commencé par le bruit d’un oiseau q...,None,"[yngvild, aspeli, polaire, maison, poupée, ara...",https://cdn.openagenda.com/main/845e82035a0349...,None,...,76685088,None,None,None,None,None,None,France (Métropole),None,None

- Nous avons bien un dataframe avec des évènements,  ce qu'il se passe d'un peu plus près.

#### Sur les 100 lignes extraites on a décidé de les filtrer par ordre décroissant afin d'obtenir des éléments de 2026 également. Pour obtenir une meilleure représentation d'une année d'historique, il faudra augmenter le nombre de lignes.

In [6]:
print(df['lastdate_end'].str[:7].value_counts())
df['lastdate_end'].str[:4].value_counts()

lastdate_end
2025-11    31
2025-12    20
2026-01    18
2026-03    15
2026-02    15
2026-04     1
Name: count, dtype: int64

lastdate_end
2025    51
2026    49
Name: count, dtype: int64

- On obtient un petit équilibre entre les deux années, pour le moment cela nous convient.

### Regardons d'un peu plus près notre dataframe
#### On va déjà regarder si le nombre de lignes correspond bien à ce que l'on voulait

In [7]:
df_shape = df.shape
print(f"Nous avons {df_shape[0]} lignes et {df_shape[1]} colonnes dans notre dataframe.")

Nous avons 100 lignes et 56 colonnes dans notre dataframe.

#### Regardons les colonnes que nous avons. Nous pourrons décider déjà d'un point de vu métier ce qui nous paraît intéressant.

In [8]:
df.columns

Index(['uid', 'slug', 'canonicalurl', 'title_fr', 'description_fr',
       'longdescription_fr', 'conditions_fr', 'keywords_fr', 'image',
       'imagecredits', 'thumbnail', 'originalimage', 'updatedat',
       'daterange_fr', 'firstdate_begin', 'firstdate_end', 'lastdate_begin',
       'lastdate_end', 'timings', 'accessibility', 'accessibility_label_fr',
       'location_uid', 'location_coordinates', 'location_name',
       'location_address', 'location_district', 'location_insee',
       'location_postalcode', 'location_city', 'location_department',
       'location_region', 'location_countrycode', 'location_image',
       'location_imagecredits', 'location_phone', 'location_website',
       'location_links', 'location_tags', 'location_description_fr',
       'location_access_fr', 'attendancemode', 'onlineaccesslink', 'status',
       'age_min', 'age_max', 'originagenda_title', 'originagenda_uid',
       'contributor_email', 'contributor_contactnumber',
       'contributor_contactname', 'contributor_contactposition',
       'contributor_organization', 'category', 'country_fr', 'registration',
       'links'],
      dtype='object')

- **Les éléments non indispensables d'un point de vu métier** : 
    - "image", "imagecredits","thumbnail","originalimage","accessibility"
    - "location_coordinates", "location_city","location_insee","location_department"
    - "location_region","location_countrycode","location_image","location_imagecredits","location_tags"
    - "attendancemode", "onlineaccesslink","country_fr","registration","links","originagenda_uid"
    - Intéressant de garder qu'une date qui comprend la date de début et de de fin ainsi que la date que nous avons sélectionné / Nous traiterons avec plus d'attention les dates lorsque nous préparerons les métadonnées

#### Colonnes à enlever du point de vu métier.

In [9]:
col_business_side = [
    "image", "imagecredits","thumbnail","originalimage","accessibility", "location_uid",
    "location_coordinates", "location_city","location_insee","location_department",
    "location_region","location_countrycode","location_image","location_imagecredits","location_tags",
    "attendancemode", "onlineaccesslink","country_fr","registration","links","originagenda_uid"
    ]
len(col_business_side)

21

* Identification de 21 colonnes non pertinentes pour notre projet d'un point de vu métier

#### Examinons les différentes dates possibles

In [10]:
df[["updatedat","daterange_fr","firstdate_begin","firstdate_end","lastdate_begin","lastdate_end","timings"]]

,updatedat,daterange_fr,firstdate_begin,firstdate_end,lastdate_begin,lastdate_end,timings
0,2025-09-24T08:48:05+00:00,24 mars - 1 avril 2026,2026-03-24T13:30:00+00:00,2026-03-24T14:30:00+00:00,2026-04-01T08:00:00+00:00,2026-04-01T09:00:00+00:00,"[{""begin"": ""2026-03-24T14:30:00+01:00"", ""end"":..."
1,2025-10-29T14:03:41+00:00,19 - 28 mars 2026,2026-03-19T18:30:00+00:00,2026-03-19T20:10:00+00:00,2026-03-28T17:00:00+00:00,2026-03-28T18:40:00+00:00,"[{""begin"": ""2026-03-19T19:30:00+01:00"", ""end"":..."
2,2025-06-25T15:52:36+00:00,"Mercredi 25 mars 2026, 19h30",2026-03-25T18:30:00+00:00,2026-03-25T21:00:00+00:00,2026-03-25T18:30:00+00:00,2026-03-25T21:00:00+00:00,"[{""begin"": ""2026-03-25T19:30:00+01:00"", ""end"":..."
3,2025-09-01T15:38:05+00:00,"Lundi 23 mars 2026, 20h00",2026-03-23T19:00:00+00:00,2026-03-23T20:30:00+00:00,2026-03-23T19:00:00+00:00,2026-03-23T20:30:00+00:00,"[{""begin"": ""2026-03-23T20:00:00+01:00"", ""end"":..."
4,2025-06-25T15:53:20+00:00,17 - 22 mars 2026,2026-03-17T19:00:00+00:00,2026-03-17T20:30:00+00:00,2026-03-22T19:00:00+00:00,2026-03-22T20:30:00+00:00,"[{""begin"": ""2026-03-17T20:00:00+01:00"", ""end"":..."
...,...,...,...,...,...,...,...
95,2025-10-28T15:15:25+00:00,"Mercredi 26 novembre, 13h30",2025-11-26T12:30:00+00:00,2025-11-26T16:30:00+00:00,2025-11-26T12:30:00+00:00,2025-11-26T16:30:00+00:00,"[{""begin"": ""2025-11-26T13:30:00+01:00"", ""end"":..."
96,2025-10-29T08:16:07+00:00,"Mercredi 26 novembre, 09h00",2025-11-26T08:00:00+00:00,2025-11-26T11:00:00+00:00,2025-11-26T08:00:00+00:00,2025-11-26T11:00:00+00:00,"[{""begin"": ""2025-11-26T09:00:00+01:00"", ""end"":..."
97,2025-10-21T08:18:39+00:00,"Mardi 25 novembre, 21h30",2025-11-25T20:30:00+00:00,2025-11-25T21:30:00+00:00,2025-11-25T20:30:00+00:00,2025-11-25T21:30:00+00:00,"[{""begin"": ""2025-11-25T21:30:00+01:00"", ""end"":..."
98,2025-10-22T18:54:53+00:00,"Mardi 25 novembre, 18h30",2025-11-25T17:30:00+00:00,2025-11-25T20:00:00+00:00,2025-11-25T17:30:00+00:00,2025-11-25T20:00:00+00:00,"[{""begin"": ""2025-11-25T18:30:00+01:00"", ""end"":..."
99,2025-09-24T08:02:45+00:00,24 et 25 novembre,2025-11-24T18:00:00+00:00,2025-11-24T19:30:00+00:00,2025-11-25T18:00:00+00:00,2025-11-25T19:30:00+00:00,"[{""begin"": ""2025-11-24T19:00:00+01:00"", ""end"":..."

* Difficile d'évaluer laquelle des colonnes est la plus pertinente pour le moment. A voir lorsque nous verrons avec les métadonnées.

#### Supprimons de notre dataframe les colonnes inutiles pour le moment.

In [11]:
df_test_clean = df.drop(columns=col_business_side)

In [12]:
df_test_clean_shape = df_test_clean.shape
print(f"Nous avons {df_shape[0]} lignes et {df_shape[1]} colonnes dans notre dataframe.")
print(f"Nous avons {df_test_clean_shape[0]} lignes et {df_test_clean_shape[1]} colonnes après suppression des colonnes inutiles du point de vu métier.")

Nous avons 100 lignes et 56 colonnes dans notre dataframe.
Nous avons 100 lignes et 35 colonnes après suppression des colonnes inutiles du point de vu métier.

#### Regardons par identifiant si nous remarquons des doublons

In [13]:
df_test_clean["uid"]

0     66000118
1     80142793
2     63232931
3      5148482
4      1617629
        ...
95    19964080
96    21941802
97    20142148
98    33701609
99    11181718
Name: uid, Length: 100, dtype: object

In [14]:
df_test_clean["uid"].duplicated().any()

np.False_

* Pas de doublons par identifiant

#### Regardons le nombre de valeurs manquantes par variable 
#### L'objectif va être de sélectionner les colonnes inutiles d'un point de vu data cette fois.

In [15]:
df_test_clean.isnull().mean()

uid                            0.00
slug                           0.00
canonicalurl                   0.00
title_fr                       0.00
description_fr                 0.00
longdescription_fr             0.01
conditions_fr                  0.43
keywords_fr                    0.16
updatedat                      0.00
daterange_fr                   0.00
firstdate_begin                0.00
firstdate_end                  0.00
lastdate_begin                 0.00
lastdate_end                   0.00
timings                        0.00
accessibility_label_fr         0.80
location_name                  0.00
location_address               0.00
location_district              0.18
location_postalcode            0.00
location_phone                 0.93
location_website               0.90
location_links                 0.82
location_description_fr        0.78
location_access_fr             0.91
status                         0.00
age_min                        0.78
age_max                        0.57
originagenda_title             0.00
contributor_email              1.00
contributor_contactnumber      1.00
contributor_contactname        1.00
contributor_contactposition    1.00
contributor_organization       1.00
category                       1.00
dtype: float64

#### Filtrons sur les variables avec plus de 70% de valeurs manquantes afin de voir si les variables sont importantes ou non.

In [16]:
df_missed_values = df_test_clean.loc[:, df_test_clean.isnull().mean()>=0.70]
df_missed_values.isnull().mean()

accessibility_label_fr         0.80
location_phone                 0.93
location_website               0.90
location_links                 0.82
location_description_fr        0.78
location_access_fr             0.91
age_min                        0.78
contributor_email              1.00
contributor_contactnumber      1.00
contributor_contactname        1.00
contributor_contactposition    1.00
contributor_organization       1.00
category                       1.00
dtype: float64

#### Regardons à quoi ressemble ces données

In [17]:
df_missed_values

,accessibility_label_fr,location_phone,location_website,location_links,location_description_fr,location_access_fr,age_min,contributor_email,contributor_contactnumber,contributor_contactname,contributor_contactposition,contributor_organization,category
0,None,None,None,None,None,None,10.0,None,None,None,None,None,None
1,None,None,None,None,None,None,14.0,None,None,None,None,None,None
2,None,None,None,None,None,None,NaN,None,None,None,None,None,None
3,None,None,None,None,None,None,NaN,None,None,None,None,None,None
4,None,None,None,None,None,None,14.0,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,None,None,None,None,None,None,NaN,None,None,None,None,None,None
96,None,None,None,None,None,None,NaN,None,None,None,None,None,None
97,None,None,None,None,None,None,NaN,None,None,None,None,None,None
98,None,None,None,None,None,None,NaN,None,None,None,None,None,None
99,None,None,None,None,None,None,12.0,None,None,None,None,None,None

* Au vu du nombre des données manquantes et la non-utilité pour notre chatbot (pas d'éléments concernant réellement un évènement particulier) on peut supprimer ces colonnes.
* On décide de garder l'âge minimum pour le moment car cela peut être une variable intéressante par la suite

In [18]:
df_missed_values = df_test_clean.loc[
    :,
    (df_test_clean.isnull().mean() >= 0.70)
    & (df_test_clean.columns != "age_min")
]

In [19]:
df_missed_values.columns

Index(['accessibility_label_fr', 'location_phone', 'location_website',
       'location_links', 'location_description_fr', 'location_access_fr',
       'contributor_email', 'contributor_contactnumber',
       'contributor_contactname', 'contributor_contactposition',
       'contributor_organization', 'category'],
      dtype='object')

In [20]:
df_col_missed = df_missed_values.columns
print(f"On peut supprimer ces {len(df_col_missed)} colonnes.")

On peut supprimer ces 12 colonnes.

#### Suppression des colonnes manquantes

In [21]:
df_firstclean = df_test_clean.drop(columns=df_col_missed)

In [22]:
df_firstclean_shape = df_firstclean.shape
print(f"Nous avons {df_shape[0]} lignes et {df_shape[1]} colonnes dans notre dataframe.")
print(f"Nous avons {df_test_clean_shape[0]} lignes et {df_test_clean_shape[1]} colonnes après suppression des colonnes inutiles du point de vu métier.")
print(f"Nous avons {df_firstclean_shape[0]} lignes et {df_firstclean_shape[1]} colonnes après suppression des colonnes inutiles du point de vu data.")

Nous avons 100 lignes et 56 colonnes dans notre dataframe.
Nous avons 100 lignes et 35 colonnes après suppression des colonnes inutiles du point de vu métier.
Nous avons 100 lignes et 23 colonnes après suppression des colonnes inutiles du point de vu data.

## Génération de nos embeddings
#### Dans cette section, nous allons procéder à deux versions :
* Une qui va nous permettre de valider notre MVP en prenant uniquement des informations courtes et "facile" à mettre en place (sans chunk car contexte court)
* Une autre avec par exemple la description longue qui va nécessiter un chunk car le contexte sera plus grand

* Examinons les colonnes restantes pour choisir lesquelles nous allons vectoriser.

In [23]:
df_firstclean.isnull().mean()

uid                    0.00
slug                   0.00
canonicalurl           0.00
title_fr               0.00
description_fr         0.00
longdescription_fr     0.01
conditions_fr          0.43
keywords_fr            0.16
updatedat              0.00
daterange_fr           0.00
firstdate_begin        0.00
firstdate_end          0.00
lastdate_begin         0.00
lastdate_end           0.00
timings                0.00
location_name          0.00
location_address       0.00
location_district      0.18
location_postalcode    0.00
status                 0.00
age_min                0.78
age_max                0.57
originagenda_title     0.00
dtype: float64

* **Version courte** : On peut commencer par quelques éléments simples pour voir si tout fonctionne correctement :
- **tile_fr**
- **description_fr**
- **conditions_fr**

* **Version longue** : On peut commencer par quelques éléments simples pour voir si tout fonctionne correctement :
- **tile_fr**
- **longdescription_fr**
- **conditions_fr**

### Plusieurs façons de péparer le "document" avant de réaliser un chunk et de vectoriser

* Petit renommage sur les noms des variables pouvant être modifiées

In [24]:
df_firstclean = df_firstclean.rename(columns={
    "title_fr":"title",
    "description_fr":"description",
    "conditions_fr":"conditions",
    "longdescription_fr":"longdescription",
    "conditions_fr":"conditions",
    "keywords_fr":"keywords",
    "daterange_fr":"daterange_fr"
    })

In [25]:
# Création de nos deux dataframe
df_short = df_firstclean.copy()
df_long = df_firstclean.copy()

##### Première version :
* On n'applique pas de séparateurs explicites ou de libellés de sections.

In [26]:
df_short["text_for_embedding"] = (
    df_short["title"] + "\n" +
    df_short["description"].fillna("") + "\n" +
    df_short["conditions"].fillna("") + "\n")
df_short["text_for_embedding"].head(100).str.len().mean()

np.float64(143.22)

* Ne nécessite pas de traitement particulier car le contexte est court

##### Deuxième manière :
* On ajoute des éléments supplémentaires pour que ça soit plus compréhensible par le modèle. On peut supprimer _fr par exemple pour économiser quelques tokens

#### Préparation du document - Version courte
* Ajout de séparateurs explicites + remplissage des NA et retour à la ligne

In [27]:
df_long["longdescription"] = df_long["longdescription"].str.replace("<[^>]+>", " ", regex=True)

df_long["text_for_embedding"] = (
    "TITRE: " + df_long["title"] + "\n" +
    "DESCRIPTION: " + df_long["longdescription"].fillna("") + "\n" +
    "CONDITIONS: " + df_long["conditions"].fillna("") + "\n"
)
df_long["text_for_embedding"].head(100).str.len().mean()

np.float64(1154.68)

* Le contexte contient beaucoup d'éléments, cela nécessite un chunk

### Test d'un modèle d'embedding : mistral-embed
Nous allons maintenant exploiter les modèles d'embedding de Mistral, accessibles via des API serverless. Cette approche simplifie grandement notre démarche, car elle élimine la nécessité de gérer la capacité de calcul requise pour faire fonctionner ces modèles.

##### Version courte

In [50]:
# On charge notre clé API Mistral depuis env
load_dotenv()

# On active notre client mistral
client = Mistral(
    api_key=os.getenv("MISTRAL_KEY")
)

# On prend 50 textes car nous avons un nombre limité de token
texts = df_short["text_for_embedding"].astype(str).tolist()[:50]

response = client.embeddings.create(
    model="mistral-embed",
    inputs=texts
)

# TOUS les embeddings
vectors_short = np.array([item.embedding for item in response.data])

print("Nombre d'embeddings :", len(vectors_short))
print("Dimension :", len(vectors_short[0]))
print("Aperçu :", vectors_short[0][:5])

Nombre d'embeddings : 50
Dimension : 1024
Aperçu : [-0.0247345   0.00944519  0.03530884  0.00837708  0.02990723]

In [42]:
# Embeddings de deux événements différents
vec1 = np.array(vectors_short[0])
vec2 = np.array(vectors_short[1])

similarite = np.dot(vec1, vec2) / (
    np.linalg.norm(vec1) * np.linalg.norm(vec2)
)

print("Similarité :", similarite)

Similarité : 0.750204532425576

In [58]:
# Initialisation de l'index Faiss
dimension_un = vectors_short.shape[1]
index = faiss.IndexFlatL2(dimension_un)

# Ajout des embeddings à l'index
index.add(vectors_short)

# Sauvegarde de l'index sur le disque
faiss.write_index(index, "faiss_index.idx")

# Requête utilisateur / Pour utiliser une query, il faut la transformer en embeddings également
query = "musée à Paris"
query_embedding = client.embeddings.create(
    model="mistral-embed",
    inputs=[query]
).data[0].embedding

k = 5
distances, indices = index.search(
    np.array([query_embedding]).astype("float32"),
    k
)
for idx in indices[0]:
    print(f"Document {idx}: {texts[idx]}")

Document 43: La Magie de Noël aux Tuileries
Vivre le patrimoine
Entrée du lieu gratuite et attractions payantes

Document 49: Comme une impression
Vivre le patrimoine
6 / 8 / 14 € - A partir de 6 ans - Les enfants de moins de 12 ans (6 €) doivent être accompagnés par un adulte (8 ou 14 €).

Document 9: Tour de contes à la Grande Mosquée de Paris
La Cour des Contes
réservation sur hello asso de la compagnie

Document 32: Tour de contes à la Grande Mosquée de Paris
La Cour des Contes
réservation sur hello asso de la compagnie

Document 10: Ensemble 2E2M : Danses en-jeu(x)
Dans le cadre d'un partenariat avec le CRR de Paris - Ida Rubinstein
Entrée libre dans la limites des places disponibles

##### Version longue

In [45]:
# On charge notre clé API Mistral depuis env
load_dotenv()

# On active notre client mistral
client = Mistral(
    api_key=os.getenv("MISTRAL_KEY")
)

# On prend 50 textes car nous avons un nombre limité de token
texts = df_long["text_for_embedding"].astype(str).tolist()[:50]

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500, # Taille de chaque segment
    chunk_overlap=50 # Chevauchement entre les segments
    )
documents = text_splitter.create_documents(
    texts=texts,
    metadatas=[
        {"Date de fin": df_long.iloc[i]["lastdate_end"],
        "Lieu": df_long.iloc[i]["location_name"],
        "Adresse postale": df_long.iloc[i]["location_address"],
        }
        for i in range(len(texts))
        ])
response = client.embeddings.create(
    model="mistral-embed",
    inputs=texts
)
texts_for_embedding = [doc.page_content for doc in documents]
response = client.embeddings.create(
    model="mistral-embed",
    inputs=texts_for_embedding
    )
    # TOUS les embeddings
vectors_long = np.array([item.embedding for item in response.data])

In [46]:
# Initialisation de l'index Faiss
dimension = vectors_long.shape[1]
index = faiss.IndexFlatL2(dimension)

# Ajout des embeddings à l'index
index.add(vectors_long)

# Sauvegarde de l'index sur le disque
faiss.write_index(index, "faiss_index.idx")

# Requête utilisateur / Pour utiliser une query, il faut la transformer en embeddings également
query = "évènement dans le 15ème arrondissements"
query_embedding = client.embeddings.create(
    model="mistral-embed",
    inputs=[query]
).data[0].embedding

In [47]:
k = 5
distances, indices = index.search(
    np.array([query_embedding]).astype("float32"),
    k
)

In [48]:
for idx in indices[0]:
    print(f"Document {idx}: {documents[idx]}")

Document 58: page_content='Et les étudiant·e·s du CRR de Paris
 _____
  Infos pratiques  :
 🗓 Lundi 16 et mardi 17 mars 2026 - 19h 📌 CRR de Paris - Ida Rubinstein - 14 rue de Madrid, 75008 Paris 🎫 Entrée libre dans la limites des places disponibles 🔗 Infos :  https://www.ensemble2e2m.fr/crr-de-paris/  _____
  Production 2e2m  L'ensemble  2E2M  est conventionné par la DRAC-IdF pour la période 2023-2024-2025
CONDITIONS: Entrée libre dans la limites des places disponibles' metadata={'Date de fin': '2026-03-17T19:30:00+00:00', 'Lieu': 'CRR de Paris - Auditorium Marcel Landowski', 'Adresse postale': '14 rue de Madrid, 75008 Paris'}
Document 210: page_content='les recoins de ce haut lieu du XIXe, de la scène aux salles de danse jusqu’au public, irriguera l’esthétique du spectacle.' metadata={'Date de fin': '2026-01-03T21:30:00+00:00', 'Lieu': 'Comédie-Française', 'Adresse postale': '1 Place Colette, 75001 Paris'}
Document 55: page_content='et le CRR de Paris – Ida Rubinstein, avec les étudiant.e.s du département Danse.' metadata={'Date de fin': '2026-03-17T19:30:00+00:00', 'Lieu': 'CRR de Paris - Auditorium Marcel Landowski', 'Adresse postale': '14 rue de Madrid, 75008 Paris'}
Document 218: page_content='https://youtu.be/ZfP8uftJ1hQ
CONDITIONS: Prix billetterie et lunettes connectées gratuite sur réservation.' metadata={'Date de fin': '2026-01-03T16:00:00+00:00', 'Lieu': 'Comédie-Française', 'Adresse postale': '1 Place Colette, 75001 Paris'}
Document 163: page_content='heureux de débuter un nouveau partenariat avec la Philharmonie de Paris et le CMBV avec ce projet ! »' metadata={'Date de fin': '2026-01-25T19:00:00+00:00', 'Lieu': 'La Philharmonie de Paris', 'Adresse postale': '221 avenue Jean-Jaurès, 75019 Paris'}

In [34]:
# Embeddings de deux événements différents
vec1 = np.array(vectors_long[0])
vec2 = np.array(vectors_long[1])

similarite = np.dot(vec1, vec2) / (
    np.linalg.norm(vec1) * np.linalg.norm(vec2)
)

print("Similarité :", similarite)

Similarité : 0.8574976771113914

#### Résultats : on voit un résultat légèrement supérieur pour la version longue sur le test du cosinus mais il faut garder en tête que ce test se déroule uniquement sur la similarité entre 2 lignes et non tout le dataframe.

## Préparation pour l'indexation avec FAISS
#### Première étape - découpage des données si nécessaires

#### Utilisation du découpage récursif avec chevauchement
Cette méthode segmente le texte en morceaux de taille définie, avec un chevauchement entre les segments pour préserver le contexte. Par exemple, en utilisant une taille de segment de 500 caractères avec un chevauchement de 50 caractères, chaque segment partage une portion avec le précédent, assurant ainsi une continuité contextuelle.